version: '3.8'

services:
  smtp:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP port

  db:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-scripts/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
   
  # Comment 'app' section if you want to run API on your local
  app:
    build: .
    container_name: go-auth-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - smtp

volumes:
  postgres_data: