name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DATABASE_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      smtp:
        image: maildev/maildev
        ports:
          - 1025:1025
          - 1080:1080

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod download

      - name: Create test database
        run: |
          psql -h postgres -U ${{ secrets.DATABASE_USER }} -c "CREATE DATABASE go-auth-db-test;"

      - name: Run tests
        env:
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: go-auth-db-test
          SMTP_HOST: smtp
          SMTP_PORT: 1025
        run: go test ./test/...

      - name: Build Docker image 🐳
        run: docker build -t go-auth-api .